"""empty message

Revision ID: 1e357b8de8d4
Revises: 594c8f477c28
Create Date: 2022-03-16 00:44:04.165233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e357b8de8d4'
down_revision = '594c8f477c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('first_name', sa.String(length=20), nullable=False))
    op.add_column('student', sa.Column('last_name', sa.String(length=20), nullable=True))
    op.add_column('student', sa.Column('father', sa.String(length=40), nullable=True))
    op.add_column('student', sa.Column('mother', sa.String(length=40), nullable=True))
    op.add_column('student', sa.Column('courses', sa.String(length=20), nullable=True))
    op.add_column('student', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('student', sa.Column('address', sa.String(length=50), nullable=True))
    op.drop_column('student', 'city')
    op.drop_column('student', 'name')
    op.drop_column('student', 'roll')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('roll', sa.VARCHAR(length=20), nullable=True))
    op.add_column('student', sa.Column('name', sa.VARCHAR(length=20), nullable=False))
    op.add_column('student', sa.Column('city', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('student', 'address')
    op.drop_column('student', 'gender')
    op.drop_column('student', 'courses')
    op.drop_column('student', 'mother')
    op.drop_column('student', 'father')
    op.drop_column('student', 'last_name')
    op.drop_column('student', 'first_name')
    # ### end Alembic commands ###
