"""empty message

Revision ID: 594c8f477c28
Revises: 22d1648df698
Create Date: 2022-03-15 22:15:26.019752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594c8f477c28'
down_revision = '22d1648df698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('city', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'city')
    # ### end Alembic commands ###
